export const UPDATE_VIEW = 'UPDATE_VIEW';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const RECOGNIZE_USER_REQ = 'RECOGNIZE_USER_REQ';
export const RECOGNIZE_USER_RES = 'RECOGNIZE_USER_RES';
export const RECOGNIZE_USER_ERR = 'RECOGNIZE_USER_ERR';
